# Required Python packages:
#
# ansible
# openstacksdk

- hosts: all

  tasks:
  - name: 'Remove the cluster router'
    os_router:
      name: "{{ os_router }}"
      state: absent
  - name: 'Remove the cluster network'
    os_network:
      name: "{{ os_network }}"
      state: absent
