# Required Python packages:
#
# ansible
# openstacksdk

- import_playbook: common.yaml

- hosts: all
  gather_facts: no

  tasks:
  - name: 'Remove the API port'
    os_port:
      name: "{{ os_port_api }}"
      state: absent

  - name: 'Remove the Ingress port'
    os_port:
      name: "{{ os_port_ingress }}"
      state: absent

  - name: 'Remove the cluster router'
    os_router:
      name: "{{ os_router }}"
      state: absent

  - name: 'Remove the cluster network'
    os_network:
      name: "{{ os_network }}"
      state: absent
