# Roles required for installation and also for applications running in the tenant cluster
# Changes here MUST be synched with pkg/asset/installconfig/kubevirt/validation.go
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenantcluster-installer
  namespace: <tenantcluster-namespace>
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines"]
  verbs: ["get", "list", "create", "delete", "update"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances"]
  verbs: ["get", "list"]
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["network-attachment-definitions"]
  verbs: ["get"]
- apiGroups: ["subresources.kubevirt.io"]
  resources: ["virtualmachineinstances/addvolume", "virtualmachineinstances/removevolume"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenantcluster-installer
  namespace: openshift-cnv
rules:
- apiGroups: ["hco.kubevirt.io"]
  resources: ["hyperconvergeds"]
  verbs: ["get"]
